### PR TITLE
update version of request to run tests

### PR DESCRIPTION
**Pull request by laurafitzgerald**
**Motivation**
Seeing error messages when runningn pm test as version of mockgoose is out of date

**Changes**
add mongoose.Promise = global.Promise;
update version of mockgoose in package.json
tests now running

@david-martin

### CODE REVIEW

**Comment by david-martin** [comment]
@laurafitzgerald do these changes work ok locally? I'm wondering why the build is failing, but travis seems to be cutting off output at 10000 lines

**Comment by laurafitzgerald** [comment]
@david-martin the tests are running locally. although i'm targeting node 4.4.0
whereas travis is targeting 0.10.48
when i target this locally i see the same problem as in the build.

**Comment by laurafitzgerald** [comment]
@david-martin PR updated as discussed. removed global.Promise

**Review by david-martin — APPROVED** [review]
Approving this update of mockgoose to unblock tests failing for TypeError on addQueue.
Tests failing for other reason (timing out on mapping.save) can be tackled in a different PR

**Pull request merged**
