### PR TITLE
Update request to version 2.79.0

### PR DESCRIPTION
**Pull request by laurafitzgerald**

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
retest this please

**Review by grdryn — APPROVED** [review]
:ship:

**Comment by grdryn** [comment]
@laurafitzgerald we should maybe keep a list of all the template jobs that fail by default, so that they can be looked into later.

**Comment by laurafitzgerald** [comment]
@grdryn 
I documented any problems/test failures in this JIRA: https://issues.jboss.org/browse/RHMAP-12788

**Pull request merged**
