### PR TITLE
Add route to / to show setup steps immediately after provision (instead of service auth error)

### PR DESCRIPTION
**Pull request by jasonmadigan**

### CODE REVIEW

**Comment by jasonmadigan** [comment]
hey @cianclarke - just FYI, added a small fix for that thing we chatted about on a call a few weeks back. Have copied Ron's latest docs too for the setup bit.

**Comment by jasonmadigan** [comment]
hmm, actually, this doesn't look so hot after testing it. let me fix it up.

**Comment by jasonmadigan** [comment]
Okay, that's better

**Comment by wei-lee** [comment]
LGTM

**Comment by cianclarke** [comment]
@wei-lee Snap.. :-)

**Comment by jasonmadigan** [comment]
@cianclarke @wei-lee 

thanks guys!

**Comment by jasonmadigan** [comment]
will cherry-pick into `FH-v3.7.0` and do the template rebuilding

**Pull request merged**
