### PR TITLE
Move dev dependencies

### PR DESCRIPTION
**Pull request by philipgough**
@cianclarke Can we consider moving these dev dependencies into the right section unless theres a reason not too. The production build is already fairly large as is

### CODE REVIEW

**Comment by cianclarke** [comment]
Looks sensible to me!

**Comment by philipgough** [comment]
@cianclarke Thanks, feel free to merge if you feel its adequate

**Comment by cianclarke** [comment]
I'd reach out to somebody from engineering - not sure what latest steps are for template PRs but suspect it might be best to bundle with a release - maybe bundle with #67 or #79..?

**Comment by philipgough** [comment]
@jasonmadigan Opinion on this small change if you wouldn't mind

**Comment by philipgough** [comment]
Merged back as part of #79. Thanks @pb82

**Pull request closed without merging**
