### PR TITLE
Try requests via model definition, many bugfixes

### PR DESCRIPTION
**Pull request by cianclarke**
(Builds upon https://github.com/feedhenry-templates/fh-api-mapper/pull/14, best review & merge this first)

Reworks how we try requests, instead of proxying bases it off the request definition as stored at that point-in-time in the backbone model (with functionality to also try via DB definition for future expansion). 
Advantages of this:
-No more arbitrary browser headers being appended to outbound requests
-True picture of raw request/response being sent over the wire, what will be sent in future with mappings, and what will be sent in the code snippet we provide at the bottom. 
-DRYs up a lot a lot of code around proxying, and promotes future re-use when we have mappings

Also adds:
-Raw request response & raw request sections, separate from headers & collapsible. (This may be getting a bit long and unwieldy, but hadn't realised these sections would be required until looking much closer)
-Correct chevrons to expand/collapseible sections via LESS

Also removes:
-Remove unused contentType from model ( this is just another header now)
-Remove unused "tester" function
-Hotlinked font-awesome is now included via bower

Also fixes:
-Bug where headers are sent as an array of numbers, and never make it to final endpoint
-Bug where request body is not sent to serverside on saving a request
-Bug where request body is not shown when editing a model

### CODE REVIEW

**Comment by lfryc** [comment]
Tests/app startup fail on `Error: Cannot find module 'underscore'`

Except that and comments on commits, it looks good,

however when tested manually, nodejs/curl sample fail to update.

**Comment by cianclarke** [comment]
Underscore was missing from package.json, oops - fixed! 
Didn't see any comments on the commits? 
Will look at snippets issue too

**Comment by lfryc** [comment]
Ok, I've created few issues from testing the impl: https://github.com/feedhenry-templates/fh-api-mapper/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0.rc1

**Comment by lfryc** [comment]
I will merge this now though and we can address them ^ in `master`

**Pull request merged**
