### PR TITLE
Phase 1 RC1

### PR DESCRIPTION
**Pull request by cianclarke**

### CODE REVIEW

**Comment by cianclarke** [comment]
Fixes #3, #16, #17, #18, #19

**Comment by lfryc** [comment]
The remove header (`trash`) button still doesn't work correctly: https://box.everhelper.me/attachment/291156/RDL8JPN3WOc6fZHTz0IIIaeVsQ3TC1Df/496688-Na1hKMb0qQhPKe50/screen.png

**Comment by lfryc** [comment]
Can't remove headers at all, clicking on `trash` button has no effect. More specifically: Headers can be removed only when non-empty.

**Comment by lfryc** [comment]
The issues with removing headers fixed in https://github.com/cianclarke/fh-api-mapper/pull/2

**Comment by lfryc** [comment]
I've added one more commit, removing `less` from Gruntfile, into https://github.com/cianclarke/fh-api-mapper/pull/2

**Pull request merged**
