### PR TITLE
[task]: RHMAP-20306 - Add/Update Travis/CI process to use supported versions

### PR DESCRIPTION
**Pull request by camilamacedo86**

### CODE REVIEW

**Comment by camilamacedo86** [comment]
@davidffrench it is not building for the nodeJS 4. Since the 4 is deprecated I think is not valid we fixed it. What do you think? Could we leave here just testing for the NodeJS 6 and adding the engine version >=6? 

c/c @grdryn

**Comment by camilamacedo86** [comment]
It is not building for the NodeJS 6. So, I think in this case we need open an issue to solve it. @davidffrench @grdryn  What do you think? Could we deprecate this template? Can we remove it from RHMAP?

**Comment by grdryn** [comment]
@davidffrench what's the overall plan for the templates, are they all being removed altogether? I feel like I ask this question about every two weeks, but the answer seems to vary, and I can't remember what the current status is.

If they're all being removed anyway, that might save @camilamacedo86 a lot of work updating them.

**Comment by davidffrench** [comment]
@grdryn That is a great question that i also don't have a definitive answer for. The template removal won't be in the near future so at least for now we need to ensure the current templates are working with the supported platform configurations. 

the question is then if we now need to maintain template support for Node 4 since it has been deprecated but is still available as a runtime in the platform. In my opinion we shouldn't have too but this is up to Nano. @camilamacedo86 please ping Nano in the JIRA to ask this question.

**Comment by camilamacedo86** [comment]
@grdryn @davidffrench  it was my mistake. This one needs some pre-installs and all is working now. Could you approve it for we are able to merge it?

**Review by davidffrench — APPROVED** [review]

**Pull request merged**
