### PR TITLE
Add list view, with CRUDL support for requests. Headers as arrays of inputs.

### PR DESCRIPTION
**Pull request by cianclarke**

### CODE REVIEW

**Comment by cianclarke** [comment]
@lfryc Reviews on a postcard!

**Comment by lfryc** [comment]
Looking :eyes:

**Comment by cianclarke** [comment]
How's the :eyes: going? :-)

**Comment by lfryc** [comment]
:eyes: finished :-) Landed here: https://github.com/feedhenry-templates/fh-api-mapper/commit/5225b879da8a13bd98780ff4becab98b64d15500

Thanks @cianclarke

**Pull request closed without merging**
