### PR TITLE
simplify local development

### PR DESCRIPTION
**Pull request by evanshortiss**
Stuff I had issues with when I cloned this locally.

* Fix an issue with the MongoDB URL when running locally
* Update `npm start` to actually run with grunt to inject env vars etc.
* Fix README headings and update with steps for running
* Include `grunt-cli` to make running via `npm start` possible without need for global grunt installs

### CODE REVIEW

**Review by camilamacedo86 — APPROVED** [review]
The changes/code shows fine too me, however, has some error. Your code didn't pass the tests.

**Review by camilamacedo86 — DISMISSED** [review]
However, look that your code didn't pass.

`````
/home/travis/build/feedhenry-templates/fh-api-mapper/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/wide-align/node_modules/string-width/index.js:2
const stripAnsi = require('strip-ansi');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/build/feedhenry-templates/fh-api-mapper/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/wide-align/align.js:2:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
````

**Comment by evanshortiss** [comment]
Thanks for the review Camilla. This isn't something I changed, this issue is related to the use of the keyword `const` in node.js v0.10.30. node.js 0.10.30 does not support `const`.

It seems like a dependency is using `const`, not the API Mapper code. I think either we drop node.js 0.10.30 support, or fix all dependencies in the `package.json` to older versions that still work in node.js 0.10.30. What do you think @camilamacedo86?

**Comment by wtrocki** [comment]
**Thanks for contributing to api-mapper**  :1st_place_medal: 
Your change was reviewed - however project is now under minor maintenance.
Closing as outdated. Feel free to reopen.

**Pull request closed without merging**
