### PR TITLE
updated view message

### PR DESCRIPTION
**Pull request by matzew**

### CODE REVIEW

**Comment by matzew** [comment]
backporting  https://github.com/feedhenry-templates/fh-api-mapper/pull/66 to 3.12

**Comment by matzew** [comment]
@kpiwko did verifucation on OS Mbaas / Node4 of the master PR

**Comment by kpiwko** [comment]
Actually, we also need to cherry-pick this one as well into 3.12:

https://github.com/feedhenry-templates/fh-api-mapper/commit/b47640b1e447bb72912bc7b4028f84e0f342efa5
https://issues.jboss.org/browse/RHMAP-6207

**Comment by kpiwko** [comment]
There is still need to add https://github.com/feedhenry-templates/fh-api-mapper/commit/b47640b1e447bb72912bc7b4028f84e0f342efa5

Tracked via https://issues.jboss.org/browse/RHMAP-6207 which I should have reopened as well.

**Comment by kpiwko** [comment]
@matzew I would not say I did verification - just happy path ;-)

**Pull request merged**
